import Head from "next/head";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  const result = await fetch(
    "https://last-airbender-api.herokuapp.com/api/v1/characters"
  ).then((res) => res.json());
  return {
    props: {
      characters: result,
    },
  };
}

export default function Home({ characters }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Avatar Heros info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="title">
          <h1>Description of Avatar characters</h1>
        </div>
        <div className="content-box">
          {characters.map((elem) => (
            <div className="content-item" key={elem._id}>
              <img src={elem.photoUrl} alt="" />
              <h3>Name: {elem.name}</h3>
              <p>Allies: {elem.allies}</p>
              <p>Enemies: {elem.enemies}</p>
              <p>Affiliation: {elem.affiliation}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
